[package]
name = "advanced_rust_language_learning"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
criterion = "0.7.0"
num-traits = "0.2.19"
num-derive = "0.4.2"
ouroboros = "0.18.5"
thread_local = "1.1.9"