[package]
name = "candle_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
candle-core = "0.9.1"
candle-transformers = "0.9.1"
clap = "4.5.43"
hf-hub = "0.4.3"
tokenizers = "0.21.4"

[[bin]]
name = "simple"
path = "src/simple.rs"


[[bin]]
name = "cli"
path = "src/cli.rs"

